// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxJxq88KHfRwVXFt7MyUrpE8Dw28jcDV8',
    appId: '1:48294313909:web:a54ccdf2d530248882a3fc',
    messagingSenderId: '48294313909',
    projectId: 'potea-40afb',
    authDomain: 'potea-40afb.firebaseapp.com',
    storageBucket: 'potea-40afb.firebasestorage.app',
    measurementId: 'G-CV6HJ04VNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAnSVBGKrmr1PAVgcDjEC7F6GGqsrxd4A',
    appId: '1:48294313909:android:7de24108dbad28e882a3fc',
    messagingSenderId: '48294313909',
    projectId: 'potea-40afb',
    storageBucket: 'potea-40afb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHPwreC-_WbiHSJo0LfGODeSFeFsWAWMI',
    appId: '1:48294313909:ios:12a04b09ab13718382a3fc',
    messagingSenderId: '48294313909',
    projectId: 'potea-40afb',
    storageBucket: 'potea-40afb.firebasestorage.app',
    iosBundleId: 'com.example.poteaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHPwreC-_WbiHSJo0LfGODeSFeFsWAWMI',
    appId: '1:48294313909:ios:12a04b09ab13718382a3fc',
    messagingSenderId: '48294313909',
    projectId: 'potea-40afb',
    storageBucket: 'potea-40afb.firebasestorage.app',
    iosBundleId: 'com.example.poteaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxJxq88KHfRwVXFt7MyUrpE8Dw28jcDV8',
    appId: '1:48294313909:web:5d66f96e88dec27d82a3fc',
    messagingSenderId: '48294313909',
    projectId: 'potea-40afb',
    authDomain: 'potea-40afb.firebaseapp.com',
    storageBucket: 'potea-40afb.firebasestorage.app',
    measurementId: 'G-KWTFNTB2KR',
  );
}
